apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-puller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::154767946691:role/health-eks-cluster-ecr-sa-role

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::154767946691:instance-profile/eks-ingress
